Updated platform support for MacOS using arm64, and added x86_64 check  for completeness
saltstack/pytest-skip-markers pull request #36
Opened 2024-08-08 17:23 UTC by dmurphy18

On a MacOS Arm64 system, Python 3 platform.machine() returns ```arm64``` and not ```aarch64``` as on Linux Arm64 systems.

For example: Ubuntu 20.04.05 arm64 (Pi 4), platform.machine() returns ```aarch64```

Hence need a function ```is_arm64``` to check for Arm64 process based system. Added function ```is_x86_64``` for completeness.

In future, for checking on Arm64 based systems, should check ```is_aarch64() or is_arm64()```, unless you definitely know the OS that you are running on, for example: Linux use ```is_aarch64()```, or Darwin (MacOS) use ```is_arm64()```

2024-08-08 21:30 UTC, dwoz requested changes

2024-08-08 21:30 UTC, dwoz commented on src/pytestskipmarkers/utils/platform.py
> +def is_arm64() -> bool:
Why do we need both aarch64 and arm64? Let's decide on one and abstract the other?

2024-08-09 15:11 UTC, dmurphy18 commented on src/pytestskipmarkers/utils/platform.py
> +def is_arm64() -> bool:
Because on MacOS Arm64, is_aarch64 returns False, since on MacOS Arm64 systems, Python's platform.machine() returns ```arm64```.

From debug software ```DGM test/support/pkg for darwin, machine string 'arm64'```.

This will fail https://github.com/saltstack/pytest-skip-markers/blob/5fc297c52dc6dfb8f592c2c428dafcf4905b6b93/src/pytestskipmarkers/utils/platform.py#L108-L112

Also adding this to salt/utils/platform too, and about to check for the wrong assumption about is_aarch64 going to cover all Arm64 platforms.

BTW: pre-commit for this repo is being a %^*$&*%$&$#$##, then have to figure out how to release and push to PyPI so can use it in the nightly build fix.

2024-08-09 15:26 UTC, dmurphy18 commented on src/pytestskipmarkers/utils/platform.py
> +def is_arm64() -> bool:
@dwoz Perhaps it might be better to alter is_aarch64 to something along the following lines

def is_aarch64():
  if is_darwin():
     return platform.machine().startswith("arm64")
  else:
    return platform.machine().startswith("aarch64")

2024-08-09 16:39 UTC, dwoz approved these changes

2024-08-09 16:46 UTC, merged